batch_size: 2500
clip_gradient_norm: 1
clip_targets_to_zero:
- PMET_q_mm
data_dir: data/historical_PMET
dataset: camels_cl
device: cuda:0
dynamic_inputs:
- PMET_precip_ng_mm
- PMET_tmean_ng_degC
- PMET_pet_ng_mm
- PMET_glacier_mm
epochs: 5
experiment_name: historical_PMET_OGGM_on_CV_X10362001
head: regression
hidden_size: 96
initial_forget_bias: 3
learning_rate:
  0: 1e-2
  30: 5e-3
  40: 1e-3
log_interval: 5
log_n_figures: 0
log_tensorboard: true
loss: nse
metrics:
- KGE
- NSE
- Pearson-r
- Beta-KGE
- Alpha-NSE
- FMS
- FHV
- FLV
model: cudalstm
num_workers: 8
optimizer: Adam
output_activation: linear
output_dropout: 0.3
predict_last_n: 1
save_weights_every: 1
seed: 123
seq_length: 270
static_attributes:
- elev_median
- slope_mean
- forest_cover
- lake_cover
- p_mean_PMET
- pet_mean_PMET
- aridity_PMET
- high_prec_freq_PMET
- glacier_cover
- glacier_dhdt
- gauge_lat
- gauge_lon
target_variables:
- PMET_q_mm
test_basin_file: /home/rooda/OneDrive/Coding/Hydro_Patagonia/Hydro_NH_test.txt
test_end_date: 31/12/2019
test_start_date: 01/01/1990
train_basin_file: /home/rooda/OneDrive/Coding/Hydro_Patagonia/Hydro_NH_train.txt
train_end_date: 31/12/2019
train_start_date: 01/01/1990
validate_every: 20
validate_n_random_basins: 9999
validation_basin_file: /home/rooda/OneDrive/Coding/Hydro_Patagonia/Hydro_NH_validation.txt
validation_end_date: 31/12/2019
validation_start_date: 01/01/1990
